mmu: AGEBIT.h PTE.h main.cpp FaultHandler.cpp HandlerFIFO.cpp HandlerSC.cpp HandlerClock.cpp HandlerRandom.cpp HandlerLRU.cpp HandlerNRU.cpp HandlerAging.cpp
	g++ main.cpp FaultHandler.cpp HandlerFIFO.cpp HandlerSC.cpp HandlerClock.cpp HandlerRandom.cpp HandlerLRU.cpp HandlerNRU.cpp HandlerAging.cpp -o mmu
clean:
	rm mmu
