a: Operation.h a.cpp SchedulerBase.cpp SchedulerSCAN.cpp IOsystem.cpp SchedulerFIFO.cpp SchedulerSSTF.cpp SchedulerCSCAN.cpp SchedulerFSCAN.cpp
	g++ a.cpp SchedulerBase.cpp SchedulerSCAN.cpp IOsystem.cpp SchedulerFIFO.cpp SchedulerSSTF.cpp SchedulerCSCAN.cpp SchedulerFSCAN.cpp -o sched
clean:
	rm a
